[package]
name = "rustc-ice"
version = "0.1.0"
authors = ["John Gallagher <john.gallagher@crowdstrike.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
